server:
  port: 8080
# Database configuration
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: Rohit4530@#

  # JPA configuration
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
